version: '3.1'
services:
 ### nginx container #########################################
  # nginx:
  #   image: nginx:stable-alpine
  #   container_name: mv_nginx
  #   volumes:
  #   - ./services/nginx/conf.d:/etc/nginx/conf.d
  #   - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #   - "80:80"
  #   environment:
  #   - NGINX_PORT=80
  
  ### node app container #########################################
  node:
    image: node:lts
    container_name: web_jobSprider
    volumes:
      - ../app/sprider:/workspace/sprider
      - ../app/web:/workspace/web
      - ../app/api:/workspace/api
      - ../lab:/workspace/lab      
    ports:
      - "3000:3000"
    tty: true

  ### Mysql container #########################################
  # mysql:
  #   image: mysql:5.7
  #   container_name: db_mysql
  #   ports:
  #     - "3305:3306"
  #   volumes:
  #     - ./services/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
  #     - ./services/mysql/data/mysql:/var/lib/mysql/:rw
  #   # restart: always
  #   privileged: true
  #   networks:
  #     - default
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "123456"
  #     TZ: "America/Toronto"

  ### mongo container #########################################
  mongo:
    image: mongo
    # restart: always
    container_name: db_mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456

  # mongo-express:
  #   image: mongo-express
  #   # restart: always
  #   container_name: web_mongoExpress
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
